### ISSUE TITLE
一些疑问

### ISSUE THREAD

**Issue by fffii** [aikunyi/FourierGNN#17]
作者你好，我注意到在IDFT后，是用一个ffn的部分去project到未来的t个时间步，但代码中在ffn前面有一个
x = torch.matmul(x, self.embeddings_10)
请问它是很关键的部分吗
<img width="847" alt="截屏2024-08-24 20 47 17" src="https://github.com/user-attachments/assets/17baecee-25df-444a-97a1-eca666d488e7">

**Comment by aikunyi** [comment]
这个只是为了减少参数量，不是关键的部分

**Comment by fffii** [comment]
> 这个只是为了减少参数量，不是关键的部分

好的谢谢
