### ISSUE TITLE
Convolution theorem

### ISSUE THREAD

**Issue by MogicianXD** [aikunyi/FourierGNN#2]
According to the convolution theorem, the Fourier transform of a convolution of two signals equals the **pointwise product** of their
Fourier transforms.

However, the left hand of Eq. (4) is the matrix multiplication. Is it correct?

**Comment by aikunyi** [comment]
Sorry, it took so long to reply to you. Do you still have questions? Note that we conduct DFT on NT dimension while we conduct matrix multiplication on d dimension.

**Comment by MogicianXD** [comment]
Thanks. I think it's right.
